# Site settings
title: Legifina
email: legifina@ethercourt.ml
url: https://ethercourt.github.io/legifina/ # https://github.com/jeromelachaud/freelancer-theme
description: "Profitez des capacités d’une IA sur-mesure pour créer des notes d'investissement complets et gagner un temps précieux. Idéale pour les investisseurs, elle permet de libérer du temps pour vos analystes en automatisant les tâches répétitives de rédaction, leur permettant de se concentrer sur des analyses plus stratégiques. Maximisez votre retour sur investissement et réduisez vos coûts d’analyse dès aujourd'hui."
keywords: "automatisation, due diligence, IA, modèle de langage, GPT, analyse financière, modélisation financière, ratios financiers, évaluation des risques, investissement, fonds d'investissement, analystes financiers"
skills: "Accélérez la Rédaction de vos notes d'investissement grâce à l'IA"
meta_author: Abdoulaye DOUCOURE

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 212F3D #18bc9c
  primary-rgb: "33,47,61" #24,288,156"
  secondary: BDC3C7 #2c3e50
  secondary-dark: 344A5C #233140

# Footer settings
footer:
  copyright: Ethercourt.ml
  location: Location
  social: Autour du Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: facebook
    url:
  #- title:
  #  url: 
  #- title:
  #  url: 
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: PAR
  - line: FR

# Credits content
credits: 'Etherourt propose également une solution sur mesure adaptée aux <a href="">autres métiers de votre entreprise</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
