# Site settings
title: Legifina
email: legifina@ethercourt.ml
url: https://ethercourt.github.io/legifina/ # https://github.com/jeromelachaud/freelancer-theme
description: "Profitez des capacités d’une IA sur-mesure pour créer des notes d'investissement complets et gagner un temps précieux. Idéale pour les investisseurs, elle permet de libérer du temps pour vos analystes en automatisant les tâches répétitives de rédaction, leur permettant de se concentrer sur des analyses plus stratégiques. Maximisez votre retour sur investissement et réduisez vos coûts d’analyse dès aujourd'hui."
keywords: "automatisation, due diligence, IA, modèle de langage, GPT, analyse financière, modélisation financière, ratios financiers, évaluation des risques, investissement, fonds d'investissement, analystes financiers"
skills: "Accélérez la Rédaction de Due Diligence grâce à l'IA"
meta_author: Abdoulaye DOUCOURE

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
